
#import "UIColor+CSSColors.h"

@implementation UIColor (CSSColors)

/*
 * List autogenerated by a script fetching the list from http://www.w3schools.com/cssref/css_colornames.asp
 */

+ (UIColor *)aliceBlueColor
{
	// AliceBlue - 240 248 255
	return [UIColor colorWithRed:0.941 green:0.973 blue:1.000 alpha:1.000];
}

+ (UIColor *)antiqueWhiteColor
{
	// AntiqueWhite - 250 235 215
	return [UIColor colorWithRed:0.980 green:0.922 blue:0.843 alpha:1.000];
}

+ (UIColor *)aquaColor
{
	// Aqua - 0 255 255
	return [UIColor colorWithRed:0.000 green:1.000 blue:1.000 alpha:1.000];
}

+ (UIColor *)aquamarineColor
{
	// Aquamarine - 127 255 212
	return [UIColor colorWithRed:0.498 green:1.000 blue:0.831 alpha:1.000];
}

+ (UIColor *)azureColor
{
	// Azure - 240 255 255
	return [UIColor colorWithRed:0.941 green:1.000 blue:1.000 alpha:1.000];
}

+ (UIColor *)beigeColor
{
	// Beige - 245 245 220
	return [UIColor colorWithRed:0.961 green:0.961 blue:0.863 alpha:1.000];
}

+ (UIColor *)bisqueColor
{
	// Bisque - 255 228 196
	return [UIColor colorWithRed:1.000 green:0.894 blue:0.769 alpha:1.000];
}

+ (UIColor *)blanchedAlmondColor
{
	// BlanchedAlmond - 255 235 205
	return [UIColor colorWithRed:1.000 green:0.922 blue:0.804 alpha:1.000];
}

+ (UIColor *)blueVioletColor
{
	// BlueViolet - 138 43 226
	return [UIColor colorWithRed:0.541 green:0.169 blue:0.886 alpha:1.000];
}

+ (UIColor *)burlyWoodColor
{
	// BurlyWood - 222 184 135
	return [UIColor colorWithRed:0.871 green:0.722 blue:0.529 alpha:1.000];
}

+ (UIColor *)cadetBlueColor
{
	// CadetBlue - 95 158 160
	return [UIColor colorWithRed:0.373 green:0.620 blue:0.627 alpha:1.000];
}

+ (UIColor *)chartreuseColor
{
	// Chartreuse - 127 255 0
	return [UIColor colorWithRed:0.498 green:1.000 blue:0.000 alpha:1.000];
}

+ (UIColor *)chocolateColor
{
	// Chocolate - 210 105 30
	return [UIColor colorWithRed:0.824 green:0.412 blue:0.118 alpha:1.000];
}

+ (UIColor *)coralColor
{
	// Coral - 255 127 80
	return [UIColor colorWithRed:1.000 green:0.498 blue:0.314 alpha:1.000];
}

+ (UIColor *)cornflowerBlueColor
{
	// CornflowerBlue - 100 149 237
	return [UIColor colorWithRed:0.392 green:0.584 blue:0.929 alpha:1.000];
}

+ (UIColor *)cornsilkColor
{
	// Cornsilk - 255 248 220
	return [UIColor colorWithRed:1.000 green:0.973 blue:0.863 alpha:1.000];
}

+ (UIColor *)crimsonColor
{
	// Crimson - 220 20 60
	return [UIColor colorWithRed:0.863 green:0.078 blue:0.235 alpha:1.000];
}

+ (UIColor *)darkBlueColor
{
	// DarkBlue - 0 0 139
	return [UIColor colorWithRed:0.000 green:0.000 blue:0.545 alpha:1.000];
}

+ (UIColor *)darkCyanColor
{
	// DarkCyan - 0 139 139
	return [UIColor colorWithRed:0.000 green:0.545 blue:0.545 alpha:1.000];
}

+ (UIColor *)darkGoldenRodColor
{
	// DarkGoldenRod - 184 134 11
	return [UIColor colorWithRed:0.722 green:0.525 blue:0.043 alpha:1.000];
}

+ (UIColor *)darkGreyColor
{
	// DarkGrey - 169 169 169
	return [UIColor colorWithRed:0.663 green:0.663 blue:0.663 alpha:1.000];
}

+ (UIColor *)darkGreenColor
{
	// DarkGreen - 0 100 0
	return [UIColor colorWithRed:0.000 green:0.392 blue:0.000 alpha:1.000];
}

+ (UIColor *)darkKhakiColor
{
	// DarkKhaki - 189 183 107
	return [UIColor colorWithRed:0.741 green:0.718 blue:0.420 alpha:1.000];
}

+ (UIColor *)darkMagentaColor
{
	// DarkMagenta - 139 0 139
	return [UIColor colorWithRed:0.545 green:0.000 blue:0.545 alpha:1.000];
}

+ (UIColor *)darkOliveGreenColor
{
	// DarkOliveGreen - 85 107 47
	return [UIColor colorWithRed:0.333 green:0.420 blue:0.184 alpha:1.000];
}

+ (UIColor *)darkorangeColor
{
	// Darkorange - 255 140 0
	return [UIColor colorWithRed:1.000 green:0.549 blue:0.000 alpha:1.000];
}

+ (UIColor *)darkOrchidColor
{
	// DarkOrchid - 153 50 204
	return [UIColor colorWithRed:0.600 green:0.196 blue:0.800 alpha:1.000];
}

+ (UIColor *)darkRedColor
{
	// DarkRed - 139 0 0
	return [UIColor colorWithRed:0.545 green:0.000 blue:0.000 alpha:1.000];
}

+ (UIColor *)darkSalmonColor
{
	// DarkSalmon - 233 150 122
	return [UIColor colorWithRed:0.914 green:0.588 blue:0.478 alpha:1.000];
}

+ (UIColor *)darkSeaGreenColor
{
	// DarkSeaGreen - 143 188 143
	return [UIColor colorWithRed:0.561 green:0.737 blue:0.561 alpha:1.000];
}

+ (UIColor *)darkSlateBlueColor
{
	// DarkSlateBlue - 72 61 139
	return [UIColor colorWithRed:0.282 green:0.239 blue:0.545 alpha:1.000];
}

+ (UIColor *)darkSlateGrayColor
{
	// DarkSlateGray - 47 79 79
	return [UIColor colorWithRed:0.184 green:0.310 blue:0.310 alpha:1.000];
}

+ (UIColor *)darkSlateGreyColor
{
	// DarkSlateGrey - 47 79 79
	return [UIColor colorWithRed:0.184 green:0.310 blue:0.310 alpha:1.000];
}

+ (UIColor *)darkTurquoiseColor
{
	// DarkTurquoise - 0 206 209
	return [UIColor colorWithRed:0.000 green:0.808 blue:0.820 alpha:1.000];
}

+ (UIColor *)darkVioletColor
{
	// DarkViolet - 148 0 211
	return [UIColor colorWithRed:0.580 green:0.000 blue:0.827 alpha:1.000];
}

+ (UIColor *)deepPinkColor
{
	// DeepPink - 255 20 147
	return [UIColor colorWithRed:1.000 green:0.078 blue:0.576 alpha:1.000];
}

+ (UIColor *)deepSkyBlueColor
{
	// DeepSkyBlue - 0 191 255
	return [UIColor colorWithRed:0.000 green:0.749 blue:1.000 alpha:1.000];
}

+ (UIColor *)dimGrayColor
{
	// DimGray - 105 105 105
	return [UIColor colorWithRed:0.412 green:0.412 blue:0.412 alpha:1.000];
}

+ (UIColor *)dimGreyColor
{
	// DimGrey - 105 105 105
	return [UIColor colorWithRed:0.412 green:0.412 blue:0.412 alpha:1.000];
}

+ (UIColor *)dodgerBlueColor
{
	// DodgerBlue - 30 144 255
	return [UIColor colorWithRed:0.118 green:0.565 blue:1.000 alpha:1.000];
}

+ (UIColor *)fireBrickColor
{
	// FireBrick - 178 34 34
	return [UIColor colorWithRed:0.698 green:0.133 blue:0.133 alpha:1.000];
}

+ (UIColor *)floralWhiteColor
{
	// FloralWhite - 255 250 240
	return [UIColor colorWithRed:1.000 green:0.980 blue:0.941 alpha:1.000];
}

+ (UIColor *)forestGreenColor
{
	// ForestGreen - 34 139 34
	return [UIColor colorWithRed:0.133 green:0.545 blue:0.133 alpha:1.000];
}

+ (UIColor *)fuchsiaColor
{
	// Fuchsia - 255 0 255
	return [UIColor colorWithRed:1.000 green:0.000 blue:1.000 alpha:1.000];
}

+ (UIColor *)gainsboroColor
{
	// Gainsboro - 220 220 220
	return [UIColor colorWithRed:0.863 green:0.863 blue:0.863 alpha:1.000];
}

+ (UIColor *)ghostWhiteColor
{
	// GhostWhite - 248 248 255
	return [UIColor colorWithRed:0.973 green:0.973 blue:1.000 alpha:1.000];
}

+ (UIColor *)goldColor
{
	// Gold - 255 215 0
	return [UIColor colorWithRed:1.000 green:0.843 blue:0.000 alpha:1.000];
}

+ (UIColor *)goldenRodColor
{
	// GoldenRod - 218 165 32
	return [UIColor colorWithRed:0.855 green:0.647 blue:0.125 alpha:1.000];
}

+ (UIColor *)greyColor
{
	// Grey - 128 128 128
	return [UIColor colorWithRed:0.502 green:0.502 blue:0.502 alpha:1.000];
}

+ (UIColor *)greenYellowColor
{
	// GreenYellow - 173 255 47
	return [UIColor colorWithRed:0.678 green:1.000 blue:0.184 alpha:1.000];
}

+ (UIColor *)honeyDewColor
{
	// HoneyDew - 240 255 240
	return [UIColor colorWithRed:0.941 green:1.000 blue:0.941 alpha:1.000];
}

+ (UIColor *)hotPinkColor
{
	// HotPink - 255 105 180
	return [UIColor colorWithRed:1.000 green:0.412 blue:0.706 alpha:1.000];
}

+ (UIColor *)indianRedColor
{
	// IndianRed  - 205 92 92
	return [UIColor colorWithRed:0.804 green:0.361 blue:0.361 alpha:1.000];
}

+ (UIColor *)indigoColor
{
	// Indigo   - 75 0 130
	return [UIColor colorWithRed:0.294 green:0.000 blue:0.510 alpha:1.000];
}

+ (UIColor *)ivoryColor
{
	// Ivory - 255 255 240
	return [UIColor colorWithRed:1.000 green:1.000 blue:0.941 alpha:1.000];
}

+ (UIColor *)khakiColor
{
	// Khaki - 240 230 140
	return [UIColor colorWithRed:0.941 green:0.902 blue:0.549 alpha:1.000];
}

+ (UIColor *)lavenderColor
{
	// Lavender - 230 230 250
	return [UIColor colorWithRed:0.902 green:0.902 blue:0.980 alpha:1.000];
}

+ (UIColor *)lavenderBlushColor
{
	// LavenderBlush - 255 240 245
	return [UIColor colorWithRed:1.000 green:0.941 blue:0.961 alpha:1.000];
}

+ (UIColor *)lawnGreenColor
{
	// LawnGreen - 124 252 0
	return [UIColor colorWithRed:0.486 green:0.988 blue:0.000 alpha:1.000];
}

+ (UIColor *)lemonChiffonColor
{
	// LemonChiffon - 255 250 205
	return [UIColor colorWithRed:1.000 green:0.980 blue:0.804 alpha:1.000];
}

+ (UIColor *)lightBlueColor
{
	// LightBlue - 173 216 230
	return [UIColor colorWithRed:0.678 green:0.847 blue:0.902 alpha:1.000];
}

+ (UIColor *)lightCoralColor
{
	// LightCoral - 240 128 128
	return [UIColor colorWithRed:0.941 green:0.502 blue:0.502 alpha:1.000];
}

+ (UIColor *)lightCyanColor
{
	// LightCyan - 224 255 255
	return [UIColor colorWithRed:0.878 green:1.000 blue:1.000 alpha:1.000];
}

+ (UIColor *)lightGoldenRodYellowColor
{
	// LightGoldenRodYellow - 250 250 210
	return [UIColor colorWithRed:0.980 green:0.980 blue:0.824 alpha:1.000];
}

+ (UIColor *)lightGreyColor
{
	// LightGrey - 211 211 211
	return [UIColor colorWithRed:0.827 green:0.827 blue:0.827 alpha:1.000];
}

+ (UIColor *)lightGreenColor
{
	// LightGreen - 144 238 144
	return [UIColor colorWithRed:0.565 green:0.933 blue:0.565 alpha:1.000];
}

+ (UIColor *)lightPinkColor
{
	// LightPink - 255 182 193
	return [UIColor colorWithRed:1.000 green:0.714 blue:0.757 alpha:1.000];
}

+ (UIColor *)lightSalmonColor
{
	// LightSalmon - 255 160 122
	return [UIColor colorWithRed:1.000 green:0.627 blue:0.478 alpha:1.000];
}

+ (UIColor *)lightSeaGreenColor
{
	// LightSeaGreen - 32 178 170
	return [UIColor colorWithRed:0.125 green:0.698 blue:0.667 alpha:1.000];
}

+ (UIColor *)lightSkyBlueColor
{
	// LightSkyBlue - 135 206 250
	return [UIColor colorWithRed:0.529 green:0.808 blue:0.980 alpha:1.000];
}

+ (UIColor *)lightSlateGrayColor
{
	// LightSlateGray - 119 136 153
	return [UIColor colorWithRed:0.467 green:0.533 blue:0.600 alpha:1.000];
}

+ (UIColor *)lightSlateGreyColor
{
	// LightSlateGrey - 119 136 153
	return [UIColor colorWithRed:0.467 green:0.533 blue:0.600 alpha:1.000];
}

+ (UIColor *)lightSteelBlueColor
{
	// LightSteelBlue - 176 196 222
	return [UIColor colorWithRed:0.690 green:0.769 blue:0.871 alpha:1.000];
}

+ (UIColor *)lightYellowColor
{
	// LightYellow - 255 255 224
	return [UIColor colorWithRed:1.000 green:1.000 blue:0.878 alpha:1.000];
}

+ (UIColor *)limeColor
{
	// Lime - 0 255 0
	return [UIColor colorWithRed:0.000 green:1.000 blue:0.000 alpha:1.000];
}

+ (UIColor *)limeGreenColor
{
	// LimeGreen - 50 205 50
	return [UIColor colorWithRed:0.196 green:0.804 blue:0.196 alpha:1.000];
}

+ (UIColor *)linenColor
{
	// Linen - 250 240 230
	return [UIColor colorWithRed:0.980 green:0.941 blue:0.902 alpha:1.000];
}

+ (UIColor *)maroonColor
{
	// Maroon - 128 0 0
	return [UIColor colorWithRed:0.502 green:0.000 blue:0.000 alpha:1.000];
}

+ (UIColor *)mediumAquaMarineColor
{
	// MediumAquaMarine - 102 205 170
	return [UIColor colorWithRed:0.400 green:0.804 blue:0.667 alpha:1.000];
}

+ (UIColor *)mediumBlueColor
{
	// MediumBlue - 0 0 205
	return [UIColor colorWithRed:0.000 green:0.000 blue:0.804 alpha:1.000];
}

+ (UIColor *)mediumOrchidColor
{
	// MediumOrchid - 186 85 211
	return [UIColor colorWithRed:0.729 green:0.333 blue:0.827 alpha:1.000];
}

+ (UIColor *)mediumPurpleColor
{
	// MediumPurple - 147 112 219
	return [UIColor colorWithRed:0.576 green:0.439 blue:0.859 alpha:1.000];
}

+ (UIColor *)mediumSeaGreenColor
{
	// MediumSeaGreen - 60 179 113
	return [UIColor colorWithRed:0.235 green:0.702 blue:0.443 alpha:1.000];
}

+ (UIColor *)mediumSlateBlueColor
{
	// MediumSlateBlue - 123 104 238
	return [UIColor colorWithRed:0.482 green:0.408 blue:0.933 alpha:1.000];
}

+ (UIColor *)mediumSpringGreenColor
{
	// MediumSpringGreen - 0 250 154
	return [UIColor colorWithRed:0.000 green:0.980 blue:0.604 alpha:1.000];
}

+ (UIColor *)mediumTurquoiseColor
{
	// MediumTurquoise - 72 209 204
	return [UIColor colorWithRed:0.282 green:0.820 blue:0.800 alpha:1.000];
}

+ (UIColor *)mediumVioletRedColor
{
	// MediumVioletRed - 199 21 133
	return [UIColor colorWithRed:0.780 green:0.082 blue:0.522 alpha:1.000];
}

+ (UIColor *)midnightBlueColor
{
	// MidnightBlue - 25 25 112
	return [UIColor colorWithRed:0.098 green:0.098 blue:0.439 alpha:1.000];
}

+ (UIColor *)mintCreamColor
{
	// MintCream - 245 255 250
	return [UIColor colorWithRed:0.961 green:1.000 blue:0.980 alpha:1.000];
}

+ (UIColor *)mistyRoseColor
{
	// MistyRose - 255 228 225
	return [UIColor colorWithRed:1.000 green:0.894 blue:0.882 alpha:1.000];
}

+ (UIColor *)moccasinColor
{
	// Moccasin - 255 228 181
	return [UIColor colorWithRed:1.000 green:0.894 blue:0.710 alpha:1.000];
}

+ (UIColor *)navajoWhiteColor
{
	// NavajoWhite - 255 222 173
	return [UIColor colorWithRed:1.000 green:0.871 blue:0.678 alpha:1.000];
}

+ (UIColor *)navyColor
{
	// Navy - 0 0 128
	return [UIColor colorWithRed:0.000 green:0.000 blue:0.502 alpha:1.000];
}

+ (UIColor *)oldLaceColor
{
	// OldLace - 253 245 230
	return [UIColor colorWithRed:0.992 green:0.961 blue:0.902 alpha:1.000];
}

+ (UIColor *)oliveColor
{
	// Olive - 128 128 0
	return [UIColor colorWithRed:0.502 green:0.502 blue:0.000 alpha:1.000];
}

+ (UIColor *)oliveDrabColor
{
	// OliveDrab - 107 142 35
	return [UIColor colorWithRed:0.420 green:0.557 blue:0.137 alpha:1.000];
}

+ (UIColor *)orangeRedColor
{
	// OrangeRed - 255 69 0
	return [UIColor colorWithRed:1.000 green:0.271 blue:0.000 alpha:1.000];
}

+ (UIColor *)orchidColor
{
	// Orchid - 218 112 214
	return [UIColor colorWithRed:0.855 green:0.439 blue:0.839 alpha:1.000];
}

+ (UIColor *)paleGoldenRodColor
{
	// PaleGoldenRod - 238 232 170
	return [UIColor colorWithRed:0.933 green:0.910 blue:0.667 alpha:1.000];
}

+ (UIColor *)paleGreenColor
{
	// PaleGreen - 152 251 152
	return [UIColor colorWithRed:0.596 green:0.984 blue:0.596 alpha:1.000];
}

+ (UIColor *)paleTurquoiseColor
{
	// PaleTurquoise - 175 238 238
	return [UIColor colorWithRed:0.686 green:0.933 blue:0.933 alpha:1.000];
}

+ (UIColor *)paleVioletRedColor
{
	// PaleVioletRed - 219 112 147
	return [UIColor colorWithRed:0.859 green:0.439 blue:0.576 alpha:1.000];
}

+ (UIColor *)papayaWhipColor
{
	// PapayaWhip - 255 239 213
	return [UIColor colorWithRed:1.000 green:0.937 blue:0.835 alpha:1.000];
}

+ (UIColor *)peachPuffColor
{
	// PeachPuff - 255 218 185
	return [UIColor colorWithRed:1.000 green:0.855 blue:0.725 alpha:1.000];
}

+ (UIColor *)peruColor
{
	// Peru - 205 133 63
	return [UIColor colorWithRed:0.804 green:0.522 blue:0.247 alpha:1.000];
}

+ (UIColor *)pinkColor
{
	// Pink - 255 192 203
	return [UIColor colorWithRed:1.000 green:0.753 blue:0.796 alpha:1.000];
}

+ (UIColor *)plumColor
{
	// Plum - 221 160 221
	return [UIColor colorWithRed:0.867 green:0.627 blue:0.867 alpha:1.000];
}

+ (UIColor *)powderBlueColor
{
	// PowderBlue - 176 224 230
	return [UIColor colorWithRed:0.690 green:0.878 blue:0.902 alpha:1.000];
}

+ (UIColor *)rosyBrownColor
{
	// RosyBrown - 188 143 143
	return [UIColor colorWithRed:0.737 green:0.561 blue:0.561 alpha:1.000];
}

+ (UIColor *)royalBlueColor
{
	// RoyalBlue - 65 105 225
	return [UIColor colorWithRed:0.255 green:0.412 blue:0.882 alpha:1.000];
}

+ (UIColor *)saddleBrownColor
{
	// SaddleBrown - 139 69 19
	return [UIColor colorWithRed:0.545 green:0.271 blue:0.075 alpha:1.000];
}

+ (UIColor *)salmonColor
{
	// Salmon - 250 128 114
	return [UIColor colorWithRed:0.980 green:0.502 blue:0.447 alpha:1.000];
}

+ (UIColor *)sandyBrownColor
{
	// SandyBrown - 244 164 96
	return [UIColor colorWithRed:0.957 green:0.643 blue:0.376 alpha:1.000];
}

+ (UIColor *)seaGreenColor
{
	// SeaGreen - 46 139 87
	return [UIColor colorWithRed:0.180 green:0.545 blue:0.341 alpha:1.000];
}

+ (UIColor *)seaShellColor
{
	// SeaShell - 255 245 238
	return [UIColor colorWithRed:1.000 green:0.961 blue:0.933 alpha:1.000];
}

+ (UIColor *)siennaColor
{
	// Sienna - 160 82 45
	return [UIColor colorWithRed:0.627 green:0.322 blue:0.176 alpha:1.000];
}

+ (UIColor *)silverColor
{
	// Silver - 192 192 192
	return [UIColor colorWithRed:0.753 green:0.753 blue:0.753 alpha:1.000];
}

+ (UIColor *)skyBlueColor
{
	// SkyBlue - 135 206 235
	return [UIColor colorWithRed:0.529 green:0.808 blue:0.922 alpha:1.000];
}

+ (UIColor *)slateBlueColor
{
	// SlateBlue - 106 90 205
	return [UIColor colorWithRed:0.416 green:0.353 blue:0.804 alpha:1.000];
}

+ (UIColor *)slateGrayColor
{
	// SlateGray - 112 128 144
	return [UIColor colorWithRed:0.439 green:0.502 blue:0.565 alpha:1.000];
}

+ (UIColor *)slateGreyColor
{
	// SlateGrey - 112 128 144
	return [UIColor colorWithRed:0.439 green:0.502 blue:0.565 alpha:1.000];
}

+ (UIColor *)snowColor
{
	// Snow - 255 250 250
	return [UIColor colorWithRed:1.000 green:0.980 blue:0.980 alpha:1.000];
}

+ (UIColor *)springGreenColor
{
	// SpringGreen - 0 255 127
	return [UIColor colorWithRed:0.000 green:1.000 blue:0.498 alpha:1.000];
}

+ (UIColor *)steelBlueColor
{
	// SteelBlue - 70 130 180
	return [UIColor colorWithRed:0.275 green:0.510 blue:0.706 alpha:1.000];
}

+ (UIColor *)tanColor
{
	// Tan - 210 180 140
	return [UIColor colorWithRed:0.824 green:0.706 blue:0.549 alpha:1.000];
}

+ (UIColor *)tealColor
{
	// Teal - 0 128 128
	return [UIColor colorWithRed:0.000 green:0.502 blue:0.502 alpha:1.000];
}

+ (UIColor *)thistleColor
{
	// Thistle - 216 191 216
	return [UIColor colorWithRed:0.847 green:0.749 blue:0.847 alpha:1.000];
}

+ (UIColor *)tomatoColor
{
	// Tomato - 255 99 71
	return [UIColor colorWithRed:1.000 green:0.388 blue:0.278 alpha:1.000];
}

+ (UIColor *)turquoiseColor
{
	// Turquoise - 64 224 208
	return [UIColor colorWithRed:0.251 green:0.878 blue:0.816 alpha:1.000];
}

+ (UIColor *)violetColor
{
	// Violet - 238 130 238
	return [UIColor colorWithRed:0.933 green:0.510 blue:0.933 alpha:1.000];
}

+ (UIColor *)wheatColor
{
	// Wheat - 245 222 179
	return [UIColor colorWithRed:0.961 green:0.871 blue:0.702 alpha:1.000];
}

+ (UIColor *)whiteSmokeColor
{
	// WhiteSmoke - 245 245 245
	return [UIColor colorWithRed:0.961 green:0.961 blue:0.961 alpha:1.000];
}

+ (UIColor *)yellowGreenColor
{
	// YellowGreen - 154 205 50
	return [UIColor colorWithRed:0.604 green:0.804 blue:0.196 alpha:1.000];
}

@end
